services:
  - type: web
    name: fastapi-app
    runtime: python
    plan: free

    rootDir: backend

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt

    startCommand: uvicorn app:app --host 0.0.0.0 --port 3000

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
